apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fflg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jbyj-tenant/rhtap-demo-app/hacbs-test-project-fflg@sha256:f6481397039b2ed82de362ae6a379103e5493f5387ebd603df523a0dafdc4580
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
